print("The itsy bitsy spider" , "climbed up" , "the waterspout.") 
print("My name is", "Python.") 
print("Monty Python.") 
print("My name is", "Python.", end=" ") 
print("Monty Python.") 
print("My name is ", end="") 
print("Monty Python.") 
print("My", "name", "is", "Monty", "Python.", sep="-") 
print("My", "name", "is", sep="_", end="*") 
print("Monty", "Python.", sep="*", end="*\n")
print("Programming","Essentials","in",sep="_",end="*") 
print("Python") 